version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout

      # Set up a remote Docker environment
      - setup_remote_docker

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      
      # Build the Docker image
      - run:
          name: Build Docker image
          command: docker build -t flask-hello-world .

      # Run tests inside the container
      - run:
          name: Test Docker container
          command: |
            docker run -d -p 5000:5000 flask-hello-world
            sleep 5
            curl -f http://localhost:5000 || exit 1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
