version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout

      # Set up a remote Docker environment so you can build images
      - setup_remote_docker

      # Build the Docker image for your Flask app
      - run:
          name: Build Docker Image
          command: docker build -t flask-hello-world .

      # Optionally, run tests inside the container
      - run:
          name: Run Tests
          command: |
            # Start the container in detached mode
            docker run -d -p 5000:5000 --name flask-app flask-hello-world
            # Give the container a few seconds to start
            sleep 5
            # Check that the app responds with "Hello, World from Flask!"
            curl -f http://localhost:5000 || (docker logs flask-app && exit 1)
            # Stop the container
            docker stop flask-app

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
